name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./разработка мобилок/ShopApp
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug
        working-directory: ./разработка мобилок/ShopApp
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: разработка мобилок/ShopApp/app/build/outputs/apk/debug/app-debug.apk
